[package]
name = "librbf"
version = "0.1.0"
authors = ["Luka Dornhecker <luka.dornhecker@gmail.com>"]
edition = "2021"

[dependencies]
chumsky = "0.8.0"
ariadne = "0.1.5"
dynasm = "1.0"
dynasmrt = "1.0"
libc = "0.2.48"
