[package]
name = "librbf"
version = "0.1.0"
authors = ["Luka Dornhecker"]
edition = "2024"

[dependencies]
dynasm = "5.0"
dynasmrt = "5.0"
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "compile"
harness = false

[[bench]]
name = "run"
harness = false
