[package]
name = "rbf"
version = "0.1.0"
authors = ["Luka Dornhecker <luka.dornhecker@gmail.com>"]
description = "Optimizing Brainfuck JIT interpreter"

[dependencies]
librbf = { path = "../librbf", version = "0.1.0" }
clap = "2.32"